call plug#begin('~/.local/share/nvim/plugins')
Plug 'Raimondi/delimitMate'
Plug 'aaronbieber/vim-quicktask'
Plug 'sjl/badwolf'
Plug 'easymotion/vim-easymotion'
Plug 'sheerun/vim-polyglot'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'myusuf3/numbers.vim'
Plug 'neomake/neomake'
Plug 'dojoteef/neomake-autolint'
Plug 'vim-airline/vim-airline'
Plug 'tpope/vim-surround'
call plug#end()
